import { readFile } from "node:fs/promises";

/**
 * Report build issues for contributor spotlight files.
 *
 * This script is used by GitHub Actions to report issues found during the build process.
 *
 * @param {Object} params
 * @param {import('@actions/core')} params.core - GitHub Actions core library
 * @param {string} params.issuesPath - Path to the issues.json file generated by the build
 * @param {string} params.filesPath - Path to the contributor spotlight directory
 */
export async function reportIssues({ core, issuesPath, filesPath }) {

  const issuesByPath = JSON.parse(await readFile(issuesPath, "utf8"));

  for (const [filepath, issues] of Object.entries(issuesByPath)) {
    const prefix = filesPath.replace(/\/?$/, "/");

    if (!filepath.includes(prefix)) {
      continue;
    }

    const file = filepath.replace(prefix, "");
    const messages = [];

    for (const issue of issues) {
      const {
        source = "unknown",
        ...otherFields
      } = Object.fromEntries(issue.fields);

      const payload = Object.entries(otherFields)
        .map(([key, value]) => `\x1b[38;2;37;136;235m${key}\x1b[0m: \x1b[38;2;221;0;169m${value}\x1b[0m`)
        .join(" • ");

      const message = source ? `\x1b[3m(${source})\x1b[0m ${payload}` : payload;
      messages.push(message);
    }

    const message = `Found \x1b[1m${issues.length}\x1b[0m issue(s) in \x1b[1m${file}\x1b[0m:\n${messages.map(m => `${m}`).join("\n")}`;
    core.warning(message, { file });
  }
};
